# Form implementation generated from reading ui file 'Conventer_valute_disagner.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def __init__(self):
        self.label_result = None
        self.label_icon_to = None
        self.combo_to = None
        self.btn_swap = None
        self.combo_from = None
        self.combo_from = None
        self.label_icon_from = None
        self.horizontalLayout_3 = None
        self.input_amount = None
        self.label_title = None
        self.verticalLayout = None

    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(389, 209)
        main_window.setStyleSheet("QWidget {\n"
                                  "    background-color: #09090b; \n"
                                  "    color: #ffffff;\n"
                                  "    font-family: \"Segoe UI\", sans-serif;\n"
                                  "}\n"
                                  "\n"
                                  "QLabel#label_title {\n"
                                  "    color: #e4e4e7;\n"
                                  "    font-size: 18px;\n"
                                  "    font-weight: bold;\n"
                                  "}\n"
                                  "\n"
                                  "QLabel {\n"
                                  "    font-size: 16px;\n"
                                  "    font-weight: 500;\n"
                                  "    color: #e4e4e7;\n"
                                  "}\n"
                                  "\n"
                                  "QLabel#label_result {\n"
                                  "    font-size: 36px;\n"
                                  "    font-weight: bold;\n"
                                  "    color: #a78bfa;\n"
                                  "}\n"
                                  "\n"
                                  "QDoubleSpinBox, QComboBox {\n"
                                  "    background-color: #18181b;\n"
                                  "    border: 2px solid #27272a;\n"
                                  "    border-radius: 12px;\n"
                                  "    padding: 10px 15px;\n"
                                  "    color: #ffffff;\n"
                                  "    font-size: 16px;\n"
                                  "}\n"
                                  "\n"
                                  "QDoubleSpinBox:focus, QComboBox:focus {\n"
                                  "    border: 2px solid #8b5cf6; \n"
                                  "    background-color: #1e1e24;\n"
                                  "}\n"
                                  "\n"
                                  "QComboBox::drop-down {\n"
                                  "    border: none;\n"
                                  "    padding-right: 10px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton {\n"
                                  "    background-color: #8b5cf6;\n"
                                  "    border: none;\n"
                                  "    border-radius: 12px;\n"
                                  "    color: #ffffff;\n"
                                  "    font-size: 15px;\n"
                                  "    font-weight: bold;\n"
                                  "    padding: 12px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    background-color: #7c3aed;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    background-color: #6d28d9;\n"
                                  "}")
        self.verticalLayout = QtWidgets.QVBoxLayout(main_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(parent=main_window)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAcceptDrops(False)
        self.label_title.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_title.setScaledContents(False)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.input_amount = QtWidgets.QDoubleSpinBox(parent=main_window)
        self.input_amount.setMaximumSize(QtCore.QSize(16777215, 45))
        self.input_amount.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.input_amount.setSuffix("")
        self.input_amount.setObjectName("input_amount")
        self.verticalLayout.addWidget(self.input_amount)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_icon_from = QtWidgets.QLabel(parent=main_window)
        self.label_icon_from.setMaximumSize(QtCore.QSize(32, 32))
        self.label_icon_from.setText("")
        self.label_icon_from.setObjectName("label_icon_from")
        self.horizontalLayout_3.addWidget(self.label_icon_from)
        self.combo_from = QtWidgets.QComboBox(parent=main_window)
        self.combo_from.setMaximumSize(QtCore.QSize(16777215, 50))
        self.combo_from.setObjectName("combo_from")
        self.horizontalLayout_3.addWidget(self.combo_from)
        self.btn_swap = QtWidgets.QPushButton(parent=main_window)
        self.btn_swap.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_swap.setObjectName("btn_swap")
        self.horizontalLayout_3.addWidget(self.btn_swap)
        self.combo_to = QtWidgets.QComboBox(parent=main_window)
        self.combo_to.setMaximumSize(QtCore.QSize(16777215, 50))
        self.combo_to.setObjectName("combo_to")
        self.horizontalLayout_3.addWidget(self.combo_to)
        self.label_icon_to = QtWidgets.QLabel(parent=main_window)
        self.label_icon_to.setMaximumSize(QtCore.QSize(32, 32))
        self.label_icon_to.setText("")
        self.label_icon_to.setObjectName("label_icon_to")
        self.horizontalLayout_3.addWidget(self.label_icon_to)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_result = QtWidgets.QLabel(parent=main_window)
        self.label_result.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Form"))
        self.label_title.setText(_translate("main_window", "Конвертер Валют"))
        self.btn_swap.setText(_translate("main_window", "Reverse"))
        self.label_result.setText(_translate("main_window", "TextLabel"))
